#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# operations-flow.sh — Automation script: Operations portal full flow
#
# Covers:
#   1.  Admin login (to create ops user and a test order)
#   2.  Create operations user via admin API
#   3.  Ops user login
#   4.  Operations dashboard — order counts by status
#   5.  List orders (with status filters)
#   6.  Get order detail
#   7.  Advance order through full lifecycle:
#         paid → processing → shipped → delivered
#   8.  Verify completed order is no longer advanceable
#   9.  Attempt invalid status transition (should be rejected)
#  10.  Cleanup
#
# Prerequisites:
#   - At least one order in 'paid' status must exist.
#   - Run order-journey.sh first (with mock payment gateway) to create one,
#     OR pass ORDER_NUMBER=ORD-XXXX as an env variable.
#
# Usage:
#   ./operations-flow.sh
#   ORDER_NUMBER=ORD-00001 ./operations-flow.sh
#   BASE_URL=https://your-domain.com/api/v1 ./operations-flow.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
source "$(dirname "$0")/_helpers.sh"

ADMIN_EMAIL="${ADMIN_EMAIL:-admin@example.com}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-Admin@1234}"
ADMIN_TOKEN=""
OPS_TOKEN=""

OPS_EMAIL="auto_ops_flow_$$@example.com"
OPS_PASSWORD=""   # Set after user creation (generated by server)
OPS_USER_ID=""

TARGET_ORDER_NUMBER="${ORDER_NUMBER:-}"   # Can be pre-set; otherwise discovered below
TARGET_ORDER_ID=""

echo -e "${BOLD}Product Catalog — Operations Portal Flow${RESET}"
echo -e "${DIM}Target: $BASE_URL${RESET}"

# ─── 1. Admin login ───────────────────────────────────────────────────────────
section "1. Admin Login"

step "POST /auth/login (admin)"
ADMIN_LOGIN_RESP=$(post "/auth/login" "{
  \"email\": \"$ADMIN_EMAIL\",
  \"password\": \"$ADMIN_PASSWORD\"
}")
assert_ok "Admin login succeeds" "$ADMIN_LOGIN_RESP"
ADMIN_TOKEN=$(extract "$ADMIN_LOGIN_RESP" "d['data']['accessToken']")
assert_not_empty "Admin access token received" "$ADMIN_TOKEN"
info "Admin token: ${ADMIN_TOKEN:0:40}…"

# ─── 2. Create operations user ────────────────────────────────────────────────
section "2. Create Operations User"

step "POST /admin/users — creating ops user $OPS_EMAIL"
CREATE_OPS_RESP=$(post "/admin/users" "{
  \"first_name\": \"Auto\",
  \"last_name\": \"OpsFlow\",
  \"email\": \"$OPS_EMAIL\",
  \"role\": \"operations\"
}" "$ADMIN_TOKEN")
assert_ok "Operations user created" "$CREATE_OPS_RESP"
OPS_USER_ID=$(extract "$CREATE_OPS_RESP" "d['data']['user']['id']")
# Server generates a random password and returns it in generated_password
OPS_PASSWORD=$(extract "$CREATE_OPS_RESP" "d['data']['generated_password']")
assert_not_empty "Ops user ID returned" "$OPS_USER_ID"
assert_not_empty "Generated password returned" "$OPS_PASSWORD"
info "Ops user ID: $OPS_USER_ID | Password: $OPS_PASSWORD"

# ─── 3. Ops user login ────────────────────────────────────────────────────────
section "3. Operations User Login"

step "POST /auth/login (operations user)"
OPS_LOGIN_RESP=$(post "/auth/login" "{
  \"email\": \"$OPS_EMAIL\",
  \"password\": \"$OPS_PASSWORD\"
}")
assert_ok "Ops user login succeeds" "$OPS_LOGIN_RESP"
OPS_TOKEN=$(extract "$OPS_LOGIN_RESP" "d['data']['accessToken']")
assert_not_empty "Ops access token received" "$OPS_TOKEN"
info "Ops token: ${OPS_TOKEN:0:40}…"

step "Verify ops user cannot access admin-only routes"
ADMIN_GUARD_RESP=$(get "/admin/users" "$OPS_TOKEN")
ADMIN_GUARD_SUCCESS=$(extract "$ADMIN_GUARD_RESP" "d.get('success',True)")
if [ "$ADMIN_GUARD_SUCCESS" != "True" ]; then
  pass "Operations user correctly blocked from admin routes"
else
  fail "Operations user should not access admin-only routes"
fi

# ─── 4. Order Counts (via list with status filter) ───────────────────────────
section "4. Order Counts by Status"

# No dedicated dashboard endpoint — derive counts from filtered lists
step "GET /operations/orders?status=paid — paid count"
PAID_RESP_COUNT=$(get "/operations/orders?status=paid" "$OPS_TOKEN")
assert_ok "Paid orders list returns 200" "$PAID_RESP_COUNT"
PAID_COUNT=$(extract "$PAID_RESP_COUNT" "d['data'].get('pagination',{}).get('total', len(d['data'].get('orders',[])))")
info "Paid orders: $PAID_COUNT"

step "GET /operations/orders?status=processing — processing count"
PROC_COUNT_RESP=$(get "/operations/orders?status=processing" "$OPS_TOKEN")
assert_ok "Processing orders list returns 200" "$PROC_COUNT_RESP"

step "GET /operations/orders?status=shipped — shipped count"
SHIP_COUNT_RESP=$(get "/operations/orders?status=shipped" "$OPS_TOKEN")
assert_ok "Shipped orders list returns 200" "$SHIP_COUNT_RESP"

# ─── 5. List orders ───────────────────────────────────────────────────────────
section "5. Order Listing (Operations)"

step "GET /operations/orders — all orders visible to ops"
ALL_ORDERS_RESP=$(get "/operations/orders" "$OPS_TOKEN")
assert_ok "Operations order list returns 200" "$ALL_ORDERS_RESP"
TOTAL_OPS_ORDERS=$(extract "$ALL_ORDERS_RESP" "d['data'].get('pagination',{}).get('total', len(d['data'].get('orders',[])))")
info "Total orders visible to ops: $TOTAL_OPS_ORDERS"

# Discover a target 'paid' order
if [ -z "$TARGET_ORDER_NUMBER" ]; then
  step "Looking for a 'paid' order to advance through lifecycle"
  PAID_FOR_ADVANCE=$(get "/operations/orders?status=paid" "$OPS_TOKEN")
  TARGET_ORDER_NUMBER=$(extract "$PAID_FOR_ADVANCE" "d['data']['orders'][0]['order_number']" 2>/dev/null || echo "")
  if [ -z "$TARGET_ORDER_NUMBER" ] || [ "$TARGET_ORDER_NUMBER" = "None" ]; then
    warn "No paid orders found to advance."
    warn "Create one with: ./order-journey.sh"
    warn "Or pass an order number: ORDER_NUMBER=ORD-00001 ./operations-flow.sh"
    info "Skipping status-progression tests."
    summary
  fi
  info "Discovered paid order: $TARGET_ORDER_NUMBER"
else
  info "Using pre-supplied order: $TARGET_ORDER_NUMBER"
fi

# ─── 6. Order detail ──────────────────────────────────────────────────────────
section "6. Order Detail"

step "GET /operations/orders/$TARGET_ORDER_NUMBER"
ORDER_DETAIL_RESP=$(get "/operations/orders/$TARGET_ORDER_NUMBER" "$OPS_TOKEN")
assert_ok "Order detail returns 200" "$ORDER_DETAIL_RESP"
TARGET_ORDER_ID=$(extract "$ORDER_DETAIL_RESP" "d['data']['order']['id']")
CURRENT_STATUS=$(extract "$ORDER_DETAIL_RESP" "d['data']['order']['status']")
assert_not_empty "Order ID present" "$TARGET_ORDER_ID"
info "Order $TARGET_ORDER_NUMBER — ID: $TARGET_ORDER_ID | Current status: $CURRENT_STATUS"

HISTORY_COUNT=$(extract "$ORDER_DETAIL_RESP" "len(d['data']['order'].get('status_history',[]))")
info "Status history entries: $HISTORY_COUNT"

# ─── 7. Status lifecycle progression ─────────────────────────────────────────
section "7. Status Lifecycle Progression"

# Helper to advance status — uses PUT (not PATCH)
advance_status() {
  local from_status="$1"
  local to_status="$2"
  local current
  current=$(extract "$(get "/operations/orders/$TARGET_ORDER_NUMBER" "$OPS_TOKEN")" "d['data']['order']['status']")

  if [ "$current" != "$from_status" ]; then
    info "Order is '$current', not '$from_status' — skipping $from_status→$to_status transition"
    return 0
  fi

  step "PUT /operations/orders/$TARGET_ORDER_NUMBER/status — $from_status → $to_status"
  ADVANCE_RESP=$(put "/operations/orders/$TARGET_ORDER_NUMBER/status" "{
    \"status\": \"$to_status\",
    \"note\": \"Automated by operations-flow.sh ($$)\"
  }" "$OPS_TOKEN")
  assert_ok "Status advanced to '$to_status'" "$ADVANCE_RESP"
  assert_field "Order status is now '$to_status'" "$ADVANCE_RESP" "d['data']['order']['status']" "$to_status"
  info "  $from_status → $to_status ✓"
}

# Full lifecycle: paid → processing → shipped → delivered
advance_status "paid"       "processing"
advance_status "processing" "shipped"
advance_status "shipped"    "delivered"

# Verify final status
step "GET /operations/orders/$TARGET_ORDER_NUMBER — verify final status"
FINAL_RESP=$(get "/operations/orders/$TARGET_ORDER_NUMBER" "$OPS_TOKEN")
FINAL_STATUS=$(extract "$FINAL_RESP" "d['data']['order']['status']")
info "Final status: $FINAL_STATUS"
if [ "$FINAL_STATUS" = "delivered" ]; then
  pass "Order reached 'delivered' status successfully"
else
  warn "Order is '$FINAL_STATUS' — may have started from a mid-lifecycle status"
fi

# Verify history grew
FINAL_HISTORY_COUNT=$(extract "$FINAL_RESP" "len(d['data']['order'].get('status_history',[]))")
info "Status history entries after progression: $FINAL_HISTORY_COUNT"

# ─── 8. Attempt to advance a completed order ──────────────────────────────────
section "8. Invalid Advance — Delivered Order"

step "PUT status on delivered order (should fail)"
COMPLETED_ADVANCE_RESP=$(put "/operations/orders/$TARGET_ORDER_NUMBER/status" "{
  \"status\": \"shipped\",
  \"note\": \"Should not be allowed\"
}" "$OPS_TOKEN")
COMPLETED_SUCCESS=$(extract "$COMPLETED_ADVANCE_RESP" "d.get('success',True)")
if [ "$COMPLETED_SUCCESS" != "True" ]; then
  pass "Advancing delivered order correctly rejected"
else
  fail "Delivered order should not be advanceable"
fi

# ─── 9. Invalid status transition ────────────────────────────────────────────
section "9. Invalid Status Transition"

# Find a processing order to attempt an invalid jump
step "GET /operations/orders?status=processing — find any processing order"
PROC_RESP=$(get "/operations/orders?status=processing" "$OPS_TOKEN")
PROC_ORDER=$(extract "$PROC_RESP" "d['data']['orders'][0]['order_number']" 2>/dev/null || echo "")

if [ -n "$PROC_ORDER" ] && [ "$PROC_ORDER" != "None" ] && [ "$PROC_ORDER" != "$TARGET_ORDER_NUMBER" ]; then
  step "Attempting processing → delivered (skipping shipped — invalid transition)"
  INVALID_TRANSITION_RESP=$(put "/operations/orders/$PROC_ORDER/status" "{
    \"status\": \"delivered\",
    \"note\": \"Invalid skip attempt\"
  }" "$OPS_TOKEN")
  INVALID_SUCCESS=$(extract "$INVALID_TRANSITION_RESP" "d.get('success',True)")
  if [ "$INVALID_SUCCESS" != "True" ]; then
    pass "Invalid status skip (processing→delivered) correctly rejected"
  else
    fail "Invalid status skip should have been rejected"
  fi
else
  info "No separate processing order found for invalid-transition test — skipping"
fi

# ─── Cleanup ──────────────────────────────────────────────────────────────────
section "Cleanup"

info "Ops user $OPS_EMAIL (ID: $OPS_USER_ID) remains in DB."
info "Remove with: DELETE FROM users WHERE email='$OPS_EMAIL';"
info "Or re-run admin-flow.sh which also cleans up its ops user."

summary
